### ISSUE TITLE
PHP trader extension

### ISSUE THREAD

**Issue by sanis** [nfq-technologies/docker-images#4]
Could you please introduce PHP trader extension for PHP 5.6 and if it's possible PHP 7.0 and PHP 7.1?

https://pecl.php.net/package/trader

**Comment by dariuskt** [comment]
I'll mark this request as wontfix.

* looks like this module had no development for more than 2 years
* it wraps library that is released 10 years ago
* there no debian package for this module

there are few ways to get it for your project

* you can extend [nfqlt/php56-fpm](https://hub.docker.com/r/nfqlt/php56-fpm/), add module and push to docker hub.
* in case you'll use it from cli only you can install it in your develop_init.sh file at runtime.
