### ISSUE TITLE
Varnish modules

### ISSUE THREAD

**Issue by sanis** [nfq-technologies/docker-images#5]
Hey,

I need your help by enabling varnish modules for varnish50 container. As we talked before it would be good to have it customisable by the flag in environment. 

You can get them by:
```sudo apt-get install varnish-modules```

Or take a look here:
https://github.com/varnish/varnish-modules

Thanks in advance.

**Comment by dariuskt** [comment]
varnish-modules added. see README for usage instructions at https://hub.docker.com/r/nfqlt/varnish50/
